### ISSUE TITLE
Which data types should we use from YAML?

### ISSUE THREAD

**Issue by philandstuff** [openregister/specification#51]
The current [JSON Representation text](http://openregister.github.io/specification/#json-representation) says:

> All field values MUST be encoded as JSON strings.

We haven't documented the rationale for this, but my understanding is that it's not generally safe to serialize integers to JSON number types because JSON doesn't directly support integers.  (There is an argument that it supports the subset of IEEE floating point numbers which happen to be integers, and indeed some json deserializers such as python's can deserialize numbers with integer values to integer types instead of floating-point types.)

That said, YAML does have support for integer types.  There's an [explicit integer tag](http://www.yaml.org/spec/1.2/spec.html#id2803828) and both the [JSON tag resolution](http://www.yaml.org/spec/1.2/spec.html#id2804356) and the [core tag resolution](http://www.yaml.org/spec/1.2/spec.html#id2805071) will assign integral value numbers to the integer tag.

This means that we don't have the same problems using integers in YAML as we have (at least in theory) from using JSON.  Should we therefore be free to use YAML integers, or should we use strings everywhere in YAML for consistency with JSON?

**Comment by philandstuff** [comment]
Just to give a concrete example:

An entry looks like this in JSON:

```
{
 "entry-number":"1",
 "item-hash":"sha256:e94c4a9ab00d951dadde848ee2c9fe51628b22ff2e0a88bff4cca6e4e6086d7a",
 "entry-timestamp":"2016-04-05T13:23:05Z"
}
```

In YAML, should the entry-number be a string or an int?

``` yaml
---
entry-number: 1
item-hash: "sha256:e94c4a9ab00d951dadde848ee2c9fe51628b22ff2e0a88bff4cca6e4e6086d7a"
entry-timestamp":"2016-04-05T13:23:05Z"
```

or

``` yaml
---
entry-number: "1"
item-hash: "sha256:e94c4a9ab00d951dadde848ee2c9fe51628b22ff2e0a88bff4cca6e4e6086d7a"
entry-timestamp":"2016-04-05T13:23:05Z"
```
